# Generated by Django 4.2.27 on 2025-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='details',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='request',
            name='topic',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='General Request', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successstory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories_videos/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
