# Generated by Django 4.2.27 on 2025-12-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_rename_details_request_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
