# Generated by Django 4.2.27 on 2026-01-08 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0009_referralrequest_remove_story_business_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Optional: Your phone or email for the business to contact you', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='industry',
            field=models.CharField(choices=[('automotive', 'Automotive'), ('restaurant', 'Restaurant & Food'), ('retail', 'Retail & Shopping'), ('health', 'Health & Wellness'), ('beauty', 'Beauty & Spa'), ('home', 'Home Services'), ('professional', 'Professional Services'), ('fitness', 'Fitness & Sports'), ('entertainment', 'Entertainment'), ('travel', 'Travel & Hospitality'), ('technology', 'Technology'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
