# Generated by Django 4.2.27 on 2026-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0013_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='requests_today',
            field=models.IntegerField(default=0),
        ),
    ]
